version: "3.9"

services:
    chisel:
        container_name: chisel
        image: jpillora/chisel:latest
        ports:
            - "1080:1080"
            - "1080:1080/udp"
        command:
            - client
            - --auth=ubuntu:ubuntu
            - https://85ptc4-5000.sse.codesandbox.io
            - 1080:socks
        restart: unless-stopped
    mipeerflix:
        container_name: mipeerflix
        build:
            context: .
        ports:
            - "1080:1080"
            - "1080:1080/udp"
        cap_drop:
            - NET_ADMIN
        restart: unless-stopped
