version: "3.9"

services:
    server:
        container_name: mipeerflix
        build:
            context: .
        ports:
            - "3000:3000"
            - "3000:3000/udp"
        restart: unless-stopped
