version: "3.9"

services:
    mipeerflix:
        container_name: server
        build:
            context: ../docker-mipeerflix
        ports:
            - "3000:3000"
            - "6800:6800"
            - "6800:6800/udp"
        restart: unless-stopped
        privileged: true
