version: "3.9"

services:
    mipeerflix:
        container_name: mipeerflix
        build:
            context: .
        ports:
            - "3000:3000"
            - "3000:3000/udp"
        cap_drop:
            - NET_ADMIN
        restart: unless-stopped
