version: "3.9"

services:
    mipeerflix:
        container_name: mipeerflix
        build:
            context: .
        environment:
            - CHISEL_CLIENT_HOST=${CHISEL_CLIENT_HOST}
        restart: unless-stopped
