version: "3.9"

services:
    mipeerflix:
        container_name: server
        build:
            context: .
        ports:
            - "3000:3000"
            - "3000:3000/udp"
        restart: unless-stopped
        privileged: true
